dist: bionic
language: python
python: "3.7"
before_install:
  - sudo apt update
  - sudo apt -y install aspell pandoc texlive-base
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - inv tests.unittest
