dist: bionic
language: python
python: "3.7"
addons:
  apt:
    update: true
    packages:
    - aspell
    - pandoc
    - texlive-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-lang-spanish
before_install:
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - inv tests.unittest
