dist: bionic
language: python
python: "3.7"
addons:
  apt:
    update: true
    packages:
    - aspell
    - pandoc
    - qpdf
    - texlive-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-lang-spanish
    - texlive-formats-extra
before_install:
  - pip install -U nox
script:
  - nox -k "test or lint"
